---
version: "2.1"
services:
  todo:
    image: nicholaswilde/todo:latest
    container_name: todo-default
    environment:
      THEME: ayu
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - todo:/todo
      - data:/data
volumes:
  todo:
  data:
